### ISSUE TITLE
Writing Images to Zip FIle

### ISSUE THREAD

**Issue by zl101** [zl101/bme590final#13]
So using zipfile, I'm able to take my Pillow Image, convert it to bytes, and write those bytes to a zip file. The resulting file however is unopenable after unzipping regardless of format (tif jpg png). Any advice on what else to try?

**Comment by mlp6** [comment]
Need a unit test that replicates that behavior to help debug that...

**Comment by zl101** [comment]
`from PIL import Image
import zipfile

if __name__ == "__main__":
    savestring = "catzipped.png"
    img = Image.open("cat2.png")
    with zipfile.ZipFile('spam.zip', 'w') as myzip:
        myzip.writestr(savestring, img.tobytes())`

**Comment by dward2** [comment]
I think the problem may be this:  you are converting the compressed image to bytes and saving those bytes  in the zip file.  When you just try to load that file containing these bytes in a photo editor, it doesn't recognize this string of bytes as an image file anymore.  I was able to write code that reversed this process to create an image (reading the bytes back into python and using Image.frombytes), but it required remembering information (mode and size) about the original picture.

Perhaps it would be better to avoid changing to bytes?  Why not just save the image file directly into the zip file?  Image.save() (<https://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.save>) saves an image into a file and then you could load this file into your Zip.

**Comment by eh158** [comment]
Was able to successfully save image into a .zip with some help from Suyash:

```
    with open("./cat.jpg", "rb") as image_file:
        encodedim = base64.b64encode(image_file.read())
    image_bytes = base64.b64decode(encodedim)
    image_buf = io.BytesIO(image_bytes)
    #savestring = "catzipped.png"
    with zipfile.ZipFile('spam.zip', 'w') as myzip:
        `myzip.writestr("cat.jpg",image_buf.read())
```
