### ISSUE TITLE
(Also posted on slack): Time to process images and latency

### ISSUE THREAD

**Issue by eh158** [zl101/bme590final#9]
What does the assignment mean when it talks about "time to process the images" and "latency for running different processing tasks"?  Are they the same thing?  From my understanding, "time to process the images" would mean the elapsed time on the server side before the processing function is called and after the processing function is called, while "latency for running different processing tasks" would be the elapsed time on the front end between sending and receiving a post request.  Is that correct? (#7 )

**Comment by mlp6** [comment]
Correct interpretation in the difference b/w the two metrics.

**Comment by eh158** [comment]
Thanks!
